/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../pch.h"
#include <jni.h>
/* Header for class mc_astar_java_MC_AStar_Java */

#ifndef _Included_mc_astar_java_MC_AStar_Java
#define _Included_mc_astar_java_MC_AStar_Java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mc_astar_java_MC_AStar_Java
 * Method:    findPath
 * Signature: (IIIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_mc_1astar_1java_MC_1AStar_1Java_findPath
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     mc_astar_java_MC_AStar_Java
 * Method:    init
 * Signature: ()Lmc_astar_java/MC_AStar_Java/MCAStarError;
 */
JNIEXPORT jobject JNICALL Java_mc_1astar_1java_MC_1AStar_1Java_init
  (JNIEnv *, jobject);

/*
 * Class:     mc_astar_java_MC_AStar_Java
 * Method:    addChunk
 * Signature: (III[J)Lmc_astar_java/MC_AStar_Java/MCAStarError;
 */
JNIEXPORT jobject JNICALL Java_mc_1astar_1java_MC_1AStar_1Java_addChunk
  (JNIEnv *, jobject, jint, jint, jint, jlongArray);

/*
 * Class:     mc_astar_java_MC_AStar_Java
 * Method:    setBlock
 * Signature: (IIIJ)Lmc_astar_java/MC_AStar_Java/MCAStarError;
 */
JNIEXPORT jobject JNICALL Java_mc_1astar_1java_MC_1AStar_1Java_setBlock
  (JNIEnv *, jobject, jint, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
