package mc_astar_java;

public enum MCAStarError
{
	/* DO NOT RENAME THESE! THEY ARE ACCESSED IN THE JNI LIB! */
	MC_ASTAR_NO_ERROR,
	MC_ASTAR_WORLD_INST_FAILED,
	MC_ASTAR_NULLPTR,
	MC_ASTAR_INVALID_POSITION,
	MC_ASTAR_ALREADY_INITIALIZED,
	MC_ASTAR_NOT_INITIALIZED,
	MC_ASTAR_ALLOCATION_FAILED;
}
